# dev env
server:
  port: 8090

spring:
# datasource
  messages:
      fallback-to-system-locale: false
  integration:
    jdbc:
      initialize-schema: embedded
#
logging:
  level:
    org.springframework.jdbc: DEBUG